name: kobi
description: A comic reader.
publish_to: 'none'

version: 0.0.16+1

environment:
  sdk: ^3.3.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  rust_lib_kobi:
    path: rust_builder
  flutter_rust_bridge: 2.9.0

  date_format: ^2.0.5
  uuid: ^4.1.0
  awesome_select: ^5.2.0
  another_xlider: ^1.0.1+2
  event: ^2.1.2
  modal_bottom_sheet: ^3.0.0-pre
  photo_view: ^0.14.0
  scrollable_positioned_list: ^0.2.3
  flutter_styled_toast: ^2.1.3
  flutter_svg: ^1.0.3
  flutter_html: 3.0.0-alpha.3
  flutter_colorpicker: ^1.0.3
  crypto: ^3.0.2
  ffi: 2.0.1
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.3.1
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
