[package]
name = "native_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native = { path = "../native" }
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["full"] }
